@extends('layouts.admin')
@section('title', 'Pemesanan')
@section('content')
<div class="page-head"><div><p class="eyebrow">BOOKING MANAGEMENT</p><h1>Pemesanan</h1><p>Periksa detail reservasi dan kelola status pembayaran pelanggan.</p></div></div>
<section class="panel"><form class="toolbar" method="get"><div class="filters"><input class="input" name="q" value="{{ request('q') }}" placeholder="Cari kode, pelanggan, lapangan"><select class="select" name="status"><option value="">Semua status</option>@foreach(['Menunggu pembayaran','Dikonfirmasi','Lunas via Midtrans','Selesai','Dibatalkan'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ $status }}</option>@endforeach</select><button class="btn secondary" type="submit">Filter</button></div><span class="help">{{ $bookings->total() }} data</span></form>
<div class="table-wrap"><table><thead><tr><th>Kode booking</th><th>Pelanggan</th><th>Venue / Lapangan</th><th>Jadwal</th><th>Pembayaran</th><th>Status</th><th></th></tr></thead><tbody>
@forelse($bookings as $booking)
    @php($statusClass = match($booking->status) {'Menunggu pembayaran' => 'pending', 'Dikonfirmasi', 'Lunas via Midtrans' => 'confirmed', 'Selesai' => 'done', 'Dibatalkan' => 'cancelled', default => ''})
    <tr><td class="primary-text">{{ $booking->code }}<span class="secondary-text">{{ $booking->created_at->format('d/m/Y H:i') }}</span></td><td>{{ $booking->customer_name }}<span class="secondary-text">{{ $booking->customer_email ?: 'Email tidak tersedia' }}</span></td><td>{{ $booking->field_name }}</td><td>{{ $booking->booking_date }}<span class="secondary-text">{{ $booking->booking_time }}</span></td><td class="primary-text">Rp {{ number_format($booking->amount, 0, ',', '.') }}</td><td><form class="row-form" method="post" action="{{ route('admin.bookings.update', $booking) }}">@csrf @method('PATCH')<select class="select" name="status" aria-label="Status {{ $booking->code }}">@foreach(['Menunggu pembayaran','Dikonfirmasi','Lunas via Midtrans','Selesai','Dibatalkan'] as $status)<option @selected($booking->status === $status)>{{ $status }}</option>@endforeach</select><button class="btn secondary small" type="submit">Simpan</button></form></td><td><form method="post" action="{{ route('admin.bookings.delete', $booking) }}" onsubmit="return confirm('Hapus booking {{ $booking->code }}?')">@csrf @method('DELETE')<button class="btn danger small" type="submit" aria-label="Hapus booking">Hapus</button></form></td></tr>
@empty<tr><td colspan="7" style="text-align:center;color:var(--muted);padding:34px">Tidak ada pemesanan yang cocok.</td></tr>@endforelse
</tbody></table></div><div class="pagination">{{ $bookings->links() }}</div></section>
@endsection